apiVersion: apps/v1
kind: Deployment
metadata:
  name: ggjjy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ggjjy
  template:
    metadata:
      labels:
        app: ggjjy
    spec:
      containers:
      - image: okteto.dev/ggjjy:latest
        name: ggjjy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d3f5baeb-63bf-4180-a85f-14e3ccc5fd04"
        - name: Vless_Path
          value: "/vl5hg55"
        - name: Vmess_UUID
          value: "d3f5baeb-63bf-4180-a85f-14e3ccc5fd04"
        - name: Vmess_Path
          value: "/vm66ioo6"
        - name: Share_Path
          value: "/v2link"
