apiVersion: apps/v1
kind: Deployment
metadata:
  name: edrfxc564
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edrfxc564
  template:
    metadata:
      labels:
        app: edrfxc564
    spec:
      containers:
      - image: okteto.dev/edrfxc564:latest
        name: edrfxc564
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "31ca89be-0414-11ed-b939-0242ac120002"
        - name: Vless_Path
          value: "/vl5tr55"
        - name: Vmess_UUID
          value: "31ca89be-0414-11ed-b939-0242ac120002"
        - name: Vmess_Path
          value: "/vm6ytgo6"
        - name: Share_Path
          value: "/v2link"
