apiVersion: v1
kind: Service
metadata:
  name: edrfxc564
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "edrfxc564"
    port: 8080
  selector:
    app: edrfxc564
