apiVersion: v1
kind: Service
metadata:
  name: ggjjy
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "ggjjy"
    port: 8080
  selector:
    app: ggjjy
